TrabalhoLocadoraMVC2/Controllers/TipoTituloController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoLocadoraMVC2.Models;

namespace TrabalhoLocadoraMVC2.Controllers
{
    [Authorize]
    public class TipoTituloController : Controller
    {
        private Repository db = new Repository();

        //
        // GET: /TipoTitulo/

        public ActionResult Index()
        {
            return View(db.TipoTitulos.ToList());
        }

        //
        // GET: /TipoTitulo/Details/5

        public ActionResult Details(long id = 0)
        {
            TipoTitulo tipotitulo = db.TipoTitulos.Find(id);
            if (tipotitulo == null)
            {
                return HttpNotFound();
            }
            return View(tipotitulo);
        }

        //
        // GET: /TipoTitulo/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TipoTitulo/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoTitulo tipotitulo)
        {
            if (ModelState.IsValid)
            {
                db.TipoTitulos.Add(tipotitulo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipotitulo);
        }

        //
        // GET: /TipoTitulo/Edit/5

        public ActionResult Edit(long id = 0)
        {
            TipoTitulo tipotitulo = db.TipoTitulos.Find(id);
            if (tipotitulo == null)
            {
                return HttpNotFound();
            }
            return View(tipotitulo);
        }

        //
        // POST: /TipoTitulo/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TipoTitulo tipotitulo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipotitulo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipotitulo);
        }

        //
        // GET: /TipoTitulo/Delete/5

        public ActionResult Delete(long id = 0)
        {
            TipoTitulo tipotitulo = db.TipoTitulos.Find(id);
            if (tipotitulo == null)
            {
                return HttpNotFound();
            }
            return View(tipotitulo);
        }

        //
        // POST: /TipoTitulo/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            TipoTitulo tipotitulo = db.TipoTitulos.Find(id);
            db.TipoTitulos.Remove(tipotitulo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TrabalhoLocadoraMVC2/Views/Shared/_IndexPartial.cshtml
@if (Request.IsAuthenticated) {
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <div class="nav-collapse collapse">
                    <a href="/Home/Index" class="brand">Projeto Locadora de Filmes</a>                    
                    <p class="navbar-text pull-right">
                        Olá, @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })!
                    <ul id="menu" class="nav navbar">
                        <li class="active">@Html.ActionLink("Inico", "Index", "Home")</li>
                        <li>@Html.ActionLink("Ator", "Index", "Ator")</li>
                        <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                        <li>@Html.ActionLink("Copia", "Index", "Copia")</li>
                        <li>@Html.ActionLink("Genero", "Index", "Genero")</li>
                        <li>@Html.ActionLink("Locacao", "Index", "Locacao")</li>
                        <li>@Html.ActionLink("Tipo Titulo", "Index", "TipoTitulo")</li>
                        <li>@Html.ActionLink("Titulo", "Index", "Titulo")</li>
                    </ul>
                    <ul id="menu" class="nav pull-right">
                        <li class="dropdown">
                            <ul class="dropdown-menu">
                              <li>
                                  @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
                                     @Html.AntiForgeryToken()
                                     <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                                  }
                              </li>
                            </ul>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="icon-align-justify"></b></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
} else {
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a href="#" class="brand">Projeto Locadora de Filmes</a>
                <ul class="nav">
                    <li>@Html.ActionLink("Novo usuário", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>@Html.ActionLink("Entrar", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
            </div>
        </div>
    </div>
    
}

TrabalhoLocadoraMVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Styles.Render("~/Content/Bootstrap/css")
        @Scripts.Render("~/Content/Bootstrap/js")
    </head>
    <body>
        <header>
            @Html.Partial("_IndexPartial")                   
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>